### ISSUE TITLE
No entiendo como resolviste, si el usuario ingresa el numero 153

### ISSUE THREAD

**Issue by Lucasutn** [lucianomaxz/java1#1]
Si el usuario ingresa el numero 153, en este caso es tu int a y cifras es igual a int a, cifra=153 seria, si a=153 en tu ciclo for va a iterar 153 veces, de todas maneras, 153 es un numero narcisista según el enunciado, y probando tu código con el 153, me da como resultado No es narcisista.()

public static void narcisista(int a){
        double cifras=a,cont=0,resto=0;
        double total=0;
        for(int i=0;i<a;i++){
            if (cifras>0) {
                resto = cifras % 10;
                total+=Math.pow(resto,a);
                cifras=cifras/10;
            }
        }

          if (a==total) {
              System.out.println("Es narcisista");
          }else {
            System.out.println("No es narcisista");
          }
}

**Comment by lucianomaxz** [comment]
Ahi te subo como debe ser xd

**Comment by Lucasutn** [comment]
Deja de copiar de stackoverflow ctm
